# -*- coding: utf-8 -*-
"""Derivable Judgement.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p5FTLrNdyiSMMArxdNx8aswaSPixX15q

# Derivable Judgement: A Statistical Decision-Making Model

## Project Scenario
You are a data analyst at a public health research organization. You've been given a dataset that contains health records of individuals from different regions, categorized by gender, age groups, lifestyle habits (smoking, exercise), and diagnosed diseases (e.g., Diabetes, Hypertension). Your task is to use statistical techniques to derive judgements about significant factors affecting disease occurrence.

## Dataset Structure
| Field Name | Data Type | Description |
| :--- | :--- | :--- |
| record_id | UUID/String | Unique identifier for each health record |
| age_group | String | Age group category (e.g., "18-25", "26-35", "36-45", "46-60", "60+") |
| age | Int | Age of individuals |
| weight | Int | Weight of Individual |
| gender | String | Gender of the individual (e.g., "Male", "Female", "Other") |
| region | String | Geographic region (e.g., "North", "South", "East", "West") |
| smoking_status | String | Smoking habit (e.g., "Smoker", "Non-Smoker", "Former Smoker") |
| exercise_frequency | String | Frequency of physical exercise (e.g., "Daily", "Weekly", "Rarely", "Never") |
| bmi | Float | Body Mass Index of the individual |
| blood_pressure | Float | Measured systolic blood pressure (mmHg) |
| diabetes | Boolean | Whether the individual has diabetes (True/False) |
| hypertension | Boolean | Whether the individual has hypertension (True/False) |
| cholesterol_level | Float | Total cholesterol level (mg/dL) |
| glucose_level | Float | Fasting glucose level (mg/dL) |
| visit_date | Date | Date of health check-up or diagnosis |
"""

import pandas as pd
import numpy as np
import uuid
from datetime import datetime, timedelta

# Set random seed for reproducibility
np.random.seed(42)

# Define dataset size
num_records = 100

# Generate fields
record_ids = [str(uuid.uuid4()) for _ in range(num_records)]
ages = np.random.randint(18, 85, size=num_records)

# Map age to age_group
def get_age_group(age):
    if 18 <= age <= 25: return "18-25"
    elif 26 <= age <= 35: return "26-35"
    elif 36 <= age <= 45: return "36-45"
    elif 46 <= age <= 60: return "46-60"
    else: return "60+"

age_groups = [get_age_group(a) for a in ages]

genders = np.random.choice(["Male", "Female", "Other"], size=num_records, p=[0.48, 0.48, 0.04])
regions = np.random.choice(["North", "South", "East", "West"], size=num_records)
smoking_statuses = np.random.choice(["Smoker", "Non-Smoker", "Former Smoker"], size=num_records, p=[0.20, 0.55, 0.25])
exercise_frequencies = np.random.choice(["Daily", "Weekly", "Rarely", "Never"], size=num_records, p=[0.15, 0.40, 0.30, 0.15])

# Continuous variables with some correlation logic
bmis = np.round(np.random.normal(26, 5, size=num_records), 1)
# Ensure BMI stays within a realistic range
bmis = np.clip(bmis, 15.0, 45.0)

# Weight derived loosely from BMI and average height assumption (1.7m)
weights = np.round(bmis * (1.7**2)).astype(int)

# Blood pressure correlated slightly with age and BMI
base_bp = 110 + (ages * 0.2) + ((bmis - 22) * 0.5)
blood_pressures = np.round(np.random.normal(base_bp, 8), 1)

# Cholesterol and Glucose levels
cholesterol_levels = np.round(np.random.normal(190 + (ages * 0.3), 30), 1)
glucose_levels = np.round(np.random.normal(90 + ((bmis - 22) * 0.8), 15), 1)

# Probabilities for chronic diseases based on risk factors
def generate_disease_status(age, bmi, smoking, base_prob):
    prob = base_prob
    if age > 50: prob += 0.15
    if bmi > 28: prob += 0.20
    if smoking == "Smoker": prob += 0.10
    return np.random.rand() < min(prob, 0.9)

diabetes = [generate_disease_status(a, b, s, 0.05) for a, b, s in zip(ages, bmis, smoking_statuses)]
hypertension = [generate_disease_status(a, b, s, 0.08) for a, b, s in zip(ages, bmis, smoking_statuses)]

# Random visit dates within the last year
start_date = datetime(2025, 9, 12)
visit_dates = [(start_date + timedelta(days=int(np.random.randint(0, 365)))).strftime('%Y-%m-%d') for _ in range(num_records)]

# Create DataFrame
df = pd.DataFrame({
    'record_id': record_ids,
    'age_group': age_groups,
    'age': ages,
    'weight': weights,
    'gender': genders,
    'region': regions,
    'smoking_status': smoking_statuses,
    'exercise_frequency': exercise_frequencies,
    'bmi': bmis,
    'blood_pressure': blood_pressures,
    'diabetes': diabetes,
    'hypertension': hypertension,
    'cholesterol_level': cholesterol_levels,
    'glucose_level': glucose_levels,
    'visit_date': visit_dates
})

# Display the first few rows of the generated dataset
df.head()

"""## 1. Hypothesis Formulation
*   **Hypothesis 1:**
    *   **$H_0$:** Smoking status has no effect on Diabetes prevalence.
    *   **$H_1$:** Smoking status significantly affects Diabetes prevalence.
mean BMI compared to those without.


"""

# H_0: Smoking status has no effect on Diabetes prevalence.
# H_1: Smoking status significantly affects Diabetes prevalence.

# So for the claim of this hypothesis we use Chi-square test to claim the hypothsis.
# So for the statistics we have ti import our library first.
from scipy.stats import chi2_contingency

# Now we have to make the contengency tabel to see clearly the data.
contengency_table = pd.crosstab(df['smoking_status'] , df['diabetes'], margins=True, margins_name= 'Total')
contengency_table

# state the observed frequency.
obs = np.array([[17, 2],
               [45, 8],
               [22, 6]])

# Perfrom the chi-sqaure test.
stat, p, dof, expected = chi2_contingency(obs)

print(f"χ² = {stat:.4f}, p = {p:.4f}, dof = {dof}")
print(f"Expected frequencies:\n{expected}")

alpha = 0.05
if p <= alpha:
    print(f"Reject H₀: Smoking status significantly affects Diabetes prevalence (p = {p:.4f})")
else:
    print(f"Fail to reject H₀: No significant association between Smoking status and Diabetes prevalence (p = {p:.4f})")

"""#  2 .**Hypothesis 2:**
  *   **$H_0$:** There is no difference in the mean BMI between individuals with and without Hypertension.
  *   **$H_1$:** Individuals with Hypertension have a significantly higher mean BMI compared to those without.

"""

from scipy.stats import ttest_ind
# Hypothesis 2:
# H0 : There is no difference in the mean BMI between individuals with and without Hypertension.
# H1 : Individuals with Hypertension have a significantly higher mean BMI compared to those without.


# Split BMI by hypertension status
bmi_hypertension = df[df['hypertension'] == True]['bmi']
bmi_no_hypertension = df[df['hypertension'] == False]['bmi']

# One-tailed Welch's t-test
stat, p = ttest_ind(bmi_hypertension, bmi_no_hypertension,
                    equal_var=False,
                    alternative='greater')

print(f"t = {stat:.4f}, p = {p:.4f}")
print(f"Mean BMI (Hypertension):     {bmi_hypertension.mean():.2f}")
print(f"Mean BMI (No Hypertension):  {bmi_no_hypertension.mean():.2f}")
print(f"Mean difference:             {bmi_hypertension.mean() - bmi_no_hypertension.mean():.2f}")

alpha = 0.05
if p <= alpha:
    print(f"\nReject H₀: Individuals with Hypertension have a significantly higher mean BMI (p = {p:.4f})")
else:
    print(f"\nFail to reject H₀: No significant evidence that Hypertension group has higher mean BMI (p = {p:.4f})")

"""## 3. Confidence Intervals
Calculate the confidence intervals (e.g., 95%) for key numerical data like `age`, `weight`, and `bmi` to estimate the population parameters.


"""

import scipy.stats as stats
import numpy as np
# Confidence Interval for the numeric column like age, weight and bmi.
# so we make one function to calculate the confidence interval.

def Confidence_interval(data, confidence = 0.95):
  n = len(data)
  mean = np.mean(data)
  std = np.std(data)

  standard_error = std / np.sqrt(n)

  critical_value = stats.t.ppf(
        (1 + confidence) / 2,
        df=n-1
    )

  margin_of_error = critical_value * standard_error

  lower = mean - margin_of_error
  upper = mean + margin_of_error

  return mean, lower, upper

# Now calultate for the age, bmi  and weight.
ci_age = tuple(Confidence_interval(df['age']))
ci_bmi = tuple(Confidence_interval(df['bmi']))
ci_weight = tuple(Confidence_interval(df['weight']))


variables = {
    "Age": df["age"],
    "Weight": df["weight"],
    "BMI": df["bmi"]
}

results = []

for name, data in variables.items():
    mean, lower, upper = Confidence_interval(data)

    results.append({
        "Variable": name,
        "Mean": mean,
        "Lower CI": lower,
        "Upper CI": upper
    })

ci_results = pd.DataFrame(results)

ci_results.round(2)

"""## 4. ANOVA Test
Perform a one-way Analysis of Variance (ANOVA) test to determine if numerical metrics (like cholesterol_level or glucose_level) significantly differ across multiple independent age_groups.
"""

# first import test from the library.
from scipy.stats import f_oneway

# Define the age group.
df["age_group"] = pd.cut(
    df["age"],
    bins=[0, 30, 50, 100],
    labels=["Young", "Middle-aged", "Older"]
)
# The Hypothesis.
# H0 = There is no significan difference between the mean of  all three age group vs cholestrol_level or Glucode level(μ1​=μ2​=μ3).
# H1 = At least one group mean is different

young = df.loc[df["age_group"] == "Young", "cholesterol_level"].dropna()
middle = df.loc[df["age_group"] == "Middle-aged", "cholesterol_level"].dropna()
older = df.loc[df["age_group"] == "Older", "cholesterol_level"].dropna()

f_stat, p_value = f_oneway(young, middle, older)

print("F-statistic:", f_stat)
print("P-value:", p_value)

alpha = 0.05
if p_value >= alpha:
  print("Fail to Reject H0: There is no significant difference between these three Age Groups.")
else :
  print('Accept the Alternate Hypothesis there is difference between these category.')

"""##5. Covariance and Correlation
Calculate the Covariance and Pearson/Spearman Correlation coefficients between continuous variables (e.g., age vs. bmi, or blood_pressure vs. glucose_level) to evaluate the strength and direction of their relationships.
"""

# Calculate the Covarience between Countinious variable of Age vs Bmi.
df[["age", "bmi"]].cov()
cov_age_bmi = df["age"].cov(df["bmi"])

print("Covariance:", cov_age_bmi)

# Covarinec between blood_presure and glucose level.
cov_bp_glucose = df["blood_pressure"].cov(df["glucose_level"])

print("Covariance:", cov_bp_glucose)

variables = [
    "age",
    "bmi",
    "blood_pressure",
    "glucose_level"
]

pearson_corr = df[variables].corr(method="pearson")
spearman_corr = df[variables].corr(method="spearman")

print("Pearson Correlation")
display(pearson_corr.round(2))

print("Spearman Correlation")
display(spearman_corr.round(2))

